### ISSUE TITLE
Missing /etc/app/application.properties triggers startup failure

### ISSUE THREAD

**Issue by AlwinEgger** [jodconverter/docker-image-jodconverter-examples#18]
Running the application without `/etc/app/application.properties` volume triggers a startup failure. 

```
docker run eugenmayer/jodconverter:rest
[...]
***************************
APPLICATION FAILED TO START
***************************

Description:

Config data location '/etc/app/' does not exist
```

**Comment by AlwinEgger** [comment]
Pull Request https://github.com/EugenMayer/docker-image-jodconverter/pull/19

**Comment by AlwinEgger** [comment]
Workaround for **Kubernetes**:

Add an args parameter containing something unused (empty `args: []` does not work as it gets omitted).
```
    spec:
      containers:
        - name: cool-pdf-converter
          image: eugenmayer/jodconverter:rest
          args: ['noop']
```
